# примеры API-запросов

@baseUrl = http://localhost:8000/api
@token1 = b5a5a5482f0dd108e76b92ec39eb8169740ca2e8
@token2 = 607feb80b950313167ac267511c6fdef79f8ae4e
@token_admin = c0d04a813fa4dcc9fd5a0854eec9415aaca5c40e

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token {{token2}}

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/42/
Content-Type: application/json
Authorization: Token {{token_admin}}

{
  "status": "OPEN"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=2
Content-Type: application/json
Authorization: Token {{token2}}

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_after=2024-01-20
Content-Type: application/json

###

# Отметить избранным/Снять метку
POST {{baseUrl}}/advertisements/42/toggle-mark/
Content-Type: application/json
Authorization: Token {{token2}}

###

# Получить список избранных
GET {{baseUrl}}/advertisements/favorites/
Content-Type: application/json
Authorization: Token {{token2}}