# Generated by Django 5.0.1 on 2024-01-22 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_advertisement_favorite_by_alter_advertisement_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='favorite_by',
            new_name='users',
        ),
    ]
